# Generated by Django 3.0 on 2025-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
         # migrations.CreateModel(
    #     name='ClientRegister_Model',
    #     fields=[
    #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #         ('username', models.CharField(max_length=30)),
    #         ('email', models.EmailField(max_length=30)),
    #         ('password', models.CharField(max_length=10)),
    #         ('phoneno', models.CharField(max_length=10)),
    #         ('country', models.CharField(max_length=30)),
    #         ('state', models.CharField(max_length=30)),
    #         ('city', models.CharField(max_length=30)),
    #     ],
    # ),

        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flow_ID', models.CharField(max_length=3000)),
                ('Source_IP', models.CharField(max_length=3000)),
                ('Source_Port', models.CharField(max_length=3000)),
                ('Destination_IP', models.CharField(max_length=3000)),
                ('Destination_Port', models.CharField(max_length=3000)),
                ('Timestamp', models.CharField(max_length=3000)),
                ('Flow_Duration', models.CharField(max_length=3000)),
                ('Total_Fwd_Packets', models.CharField(max_length=3000)),
                ('Total_Backward_Packets', models.CharField(max_length=3000)),
                ('Total_Length_of_Fwd_Packets', models.CharField(max_length=3000)),
                ('Total_Length_of_Bwd_Packets', models.CharField(max_length=3000)),
                ('Fwd_Packet_Length_Max', models.CharField(max_length=3000)),
                ('Fwd_Packet_Length_Min', models.CharField(max_length=3000)),
                ('Bwd_Packet_Length_Max', models.CharField(max_length=3000)),
                ('Flow_Bytes', models.CharField(max_length=3000)),
                ('Flow_Packets', models.CharField(max_length=3000)),
                ('Fwd_Packets', models.CharField(max_length=3000)),
                ('Bwd_Packets', models.CharField(max_length=3000)),
                ('Max_Packet_Length', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
    ]
