# Generated by Django 3.0 on 2025-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection_type',
            name='Bwd_Packet_Length_Max',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Bwd_Packets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Destination_IP',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Destination_Port',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Flow_Bytes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Flow_Duration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Flow_ID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Flow_Packets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Fwd_Packet_Length_Max',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Fwd_Packet_Length_Min',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Fwd_Packets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Max_Packet_Length',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Prediction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Source_IP',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Source_Port',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Timestamp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Total_Backward_Packets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Total_Fwd_Packets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Total_Length_of_Bwd_Packets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detection_type',
            name='Total_Length_of_Fwd_Packets',
            field=models.TextField(),
        ),
    ]
